version: '3'

services:
    konga:
        image: pantsel/konga:latest
        links:
            - kong:kong
        ports:
            - 1337:1337
        environment:
            - NODE_ENV=production
    kong:
        build:
            context: ../
            dockerfile: Dockerfile
        links:
            - kong-database:kong-database
        environment:
            - KONG_DATABASE=postgres
            - KONG_PG_HOST=kong-database
            - KONG_CASSANDRA_CONTACT_POINTS=kong-database
            - KONG_PROXY_ACCESS_LOG=/dev/stdout
            - KONG_ADMIN_ACCESS_LOG=/dev/stdout
            - KONG_PROXY_ERROR_LOG=/dev/stderr
            - KONG_ADMIN_ERROR_LOG=/dev/stderr
            - KONG_ADMIN_LISTEN=0.0.0.0:8001
            - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
        ports:
            - 8000:8000
            - 8443:8443
            - 8001:8001
            - 8444:8444
    kong-database:
        image: gaku3601/ja-postgresql:10.0
        environment:
            - POSTGRES_USER=kong
            - POSTGRES_DB=kong
        ports:
            - 5432:5432
